baseURL = 'https://tyfoza.github.io/'
defaultContentLanguage = 'cs'
title = 'Tyfoza blog'
theme = 'PaperMod'
summaryLength = 250

[params]
  defaultTheme = "auto"       # Automaticky se přepne na tmavý podle systému čtenáře
  ShowThemeToggle = true      # Přidá tlačítko pro přepínání světlý/tmavý režim nahoru
  ShowReadingTime = true      # Ukáže u článku odhad, jak dlouho se bude číst
  ShowShareButtons = false    # Vypne otravná tlačítka pro sdílení na sítě

  [params.label]
    icon = "/images/tyfoza.jpg"

  [params.cover]
    hiddenInSingle = true


[permalinks]
  posts = "/posts/:year/:month/:slug/"


[menu]
  [[menu.main]]
    identifier = "fotogalerie"
    name = "Fotogalerie"
    url = "https://sites.google.com/view/tyfotoza/"
    weight = 5

[[menu.main]]
  identifier = "3d"
  name = "3D"
  url = "/tags/3d/"
  weight = 10

[[menu.main]]
  identifier = "bastleni"
  name = "Bastlení"
  url = "/tags/bastlen%C3%AD/"
  weight = 20

[[menu.main]]
  identifier = "v-strom"
  name = "Suzuki V-Strom"
  url = "/tags/suzuki-dl-650-k9/"
  weight = 30

[[menu.main]]
name = "Další témata"
url = "/tags/"
weight = 49

[[menu.main]]
  name = "Napsat Tyfovi"
  url = "/kontakt/"
  weight = 60

[[menu.main]]
name = "Hledat"
url = "/search/"
weight = 50
[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  identifier = "archives"
  name = "Archiv"
  url = "/archives/"
  weight = 60

ignoreLogs = ['warning-goldmark-raw-html']

[outputs]
  home = ["HTML", "RSS", "JSON"]
